=== robert0714/nbiSftp/src/main/resources/serversSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      NBI temp solution Ftp schema for TWM.com.
      Copyright 2011 STI.com. All rights reserved.
    </xsd:documentation>
  </xsd:annotation>


  <xsd:element name="servers">
    <xsd:complexType>
      <xsd:sequence>
      	<xsd:element ref="server" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="server" type="ServerType"/>
  
  <xsd:complexType name="ServerType">
    <xsd:sequence>

    	<xsd:element name="ip" type="xsd:string" maxOccurs="1"
    		minOccurs="1">
    	</xsd:element>
    	<xsd:element name="port" type="xsd:string" maxOccurs="1"
    		minOccurs="0">
    	</xsd:element>
    	<xsd:element name="userName" type="xsd:string" maxOccurs="1"
    		minOccurs="0">
    	</xsd:element>
    	<xsd:element name="passwd" type="xsd:string" maxOccurs="1"
    		minOccurs="0">
    	</xsd:element>
    	<xsd:element name="sFtp" type="xsd:boolean" maxOccurs="1" minOccurs="1"></xsd:element>
    	<xsd:element name="filePatterns" type="FilePatternType"
    		maxOccurs="1" minOccurs="1">
    	</xsd:element>
    </xsd:sequence>
    <xsd:attribute name="serverName" type="xsd:string"/>
  </xsd:complexType>
  
  <xsd:complexType name="FileDetailRecordType">
  	<xsd:sequence>
  		<xsd:element name="pattern" type="xsd:string"></xsd:element>
  		<xsd:element name="remoteFolderName" type="xsd:string"></xsd:element>
  		<xsd:element name="localFolderName" type="xsd:string"></xsd:element>
  		<xsd:element name="CustomLogicClassName"  minOccurs="0" maxOccurs="1" nillable="true"  type="xsd:string"></xsd:element>
  		<xsd:element name="putOrGet" type="xsd:boolean" maxOccurs="1" minOccurs="1"></xsd:element>
  		<xsd:element name="bulkTransport" type="xsd:boolean"></xsd:element>
  		<xsd:element name="compressPut" type="xsd:boolean"></xsd:element>
  	</xsd:sequence>
  	<xsd:attribute name="description" type="xsd:string"></xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="FilePatternType">
  	<xsd:sequence>
  		<xsd:element name="filePattern" type="FileDetailRecordType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
  	</xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== robert0714/nbiSftp/src/main/resources/serversSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<servers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="serversSchema.xsd">
	<server serverName="Lynx FTP server transporting FNMS datas">
		<ip>172.27.17.202</ip>
		<port>21</port>
		<userName>ifmcollector</userName>
		<passwd>4rfv%TGB</passwd>
		<sFtp>0</sFtp>
		<filePatterns>
			<filePattern description="WBTS_RCx">
				<pattern>RCx_siteconf_yyyymmdd</pattern>				
				<remoteFolderName>Traffic/Nokia_3G/RAN/Xml/WBTS/</remoteFolderName>
				<localFolderName>TWM/Lynx/WBTS</localFolderName>
				<CustomLogicClassName>com.twm.nbi.behaviors.DynamicCustomBehaviorWBTRCx</CustomLogicClassName>
				<putOrGet>1</putOrGet>
				<bulkTransport>1</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>		
			<filePattern description="rnc_srcdata">				
				<pattern>RNC.*</pattern>				
				<remoteFolderName>/Traffic/Nokia_3G/RAN/Xml/</remoteFolderName>
				<localFolderName>TWM/Lynx/rnc</localFolderName>
				<putOrGet>1</putOrGet>
				<bulkTransport>1</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>
			<filePattern description="siteview3g">				
				<pattern>siteview3g.xls</pattern>				
				<remoteFolderName>/Traffic/Nokia_3G/RAN/Cfg</remoteFolderName>
				<localFolderName>TWM/Lynx/site</localFolderName>
				<putOrGet>1</putOrGet>
				<bulkTransport>0</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>
			<filePattern description="actual_AXC">				
				<pattern>actual_AXC_.*</pattern>				
				<remoteFolderName>/Traffic/Nokia_3G/RAN/Xml/AXC/xml/</remoteFolderName>
				<localFolderName>TWM/Lynx/actual_AXC</localFolderName>
				<putOrGet>1</putOrGet>
				<bulkTransport>1</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>
			<filePattern description="actual_FTM">				
				<pattern>actual_FTM_.*</pattern>				
				<remoteFolderName>/Traffic/Nokia_3G/RAN/Xml/WBTS/xml/</remoteFolderName>
				<localFolderName>TWM/Lynx/actual_FTM</localFolderName>
				<putOrGet>1</putOrGet>
				<bulkTransport>1</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>
			<filePattern description="TWM_ATM">				
				<pattern>.*</pattern>				
				<remoteFolderName>/Traffic/Nokia_3G/RAN/Xml/TWM_ATM</remoteFolderName>
				<localFolderName>TWM/Lynx/TWM_ATM</localFolderName>
				<putOrGet>1</putOrGet>
				<bulkTransport>1</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>			
		</filePatterns>
	</server>
	<server serverName="iPM FTP server transporting FNMS datas">
		<ip>172.18.107.76</ip>
		<port>21</port>
		<userName>irm</userName>
		<passwd>irmupload</passwd>
		<sFtp>0</sFtp>
		
		<filePatterns>
			<filePattern description="me-vpn">
				<pattern>FNMS_C17_me-vpn_\\d{8}.csv</pattern>				
				<remoteFolderName>/</remoteFolderName>
				<localFolderName>TFN/Metro</localFolderName>
				<putOrGet>0</putOrGet>
				<bulkTransport>0</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>
			<filePattern description="ip-vpn">
				<pattern>FNMS_C09_ip-vpn_\\d{8}.csv</pattern>				
				<remoteFolderName>/</remoteFolderName>
				<localFolderName>TFN/IP-VPN</localFolderName>
				<putOrGet>0</putOrGet>
				<bulkTransport>0</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>			
		</filePatterns>
	</server>
	<server serverName="iPM FTP server transporting FNMS datas">
		<ip>172.18.107.64</ip>
		<port>21</port>
		<userName>irm</userName>
		<passwd>irmupload</passwd>		
		<sFtp>0</sFtp>
		<filePatterns>			
			<filePattern description="siteview3g">
				<pattern>siteview3g.xls</pattern>
				<remoteFolderName>/</remoteFolderName>
				<localFolderName>TWM/Lynx/site</localFolderName>
				<putOrGet>0</putOrGet>
				<bulkTransport>0</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>
		</filePatterns>
	</server>
	<server serverName="iFM FTP server transporting FNMS datas">
		<ip>172.18.1.51</ip>
		<port>21</port>
		<userName>topouser</userName>
		<passwd>topouser</passwd>
		<sFtp>0</sFtp>
		
		<filePatterns>
			<filePattern description="me-vpn">
				<pattern>FNMS_C17_me-vpn_\\d{8}.csv</pattern>				
				<remoteFolderName>/ExtSD7/topodata/</remoteFolderName>
				<localFolderName>TFN/Metro</localFolderName>
				<putOrGet>0</putOrGet>
				<bulkTransport>0</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>
			<filePattern description="ip-vpn">
				<pattern>FNMS_C09_ip-vpn_\\d{8}.csv</pattern>				
				<remoteFolderName>/ExtSD7/topodata/</remoteFolderName>
				<localFolderName>TFN/IP-VPN</localFolderName>
				<putOrGet>0</putOrGet>
				<bulkTransport>0</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>
			<filePattern description="actual_AXC">
				<pattern>actual_AXC_.*</pattern>				
				<remoteFolderName>/ExtSD7/topodata/</remoteFolderName>
				<localFolderName>TWM/Lynx/actual_AXC</localFolderName>
				<putOrGet>0</putOrGet>
				<bulkTransport>1</bulkTransport>
				<compressPut>1</compressPut>
			</filePattern>
			<filePattern description="actual_FTM">
				<pattern>actual_FTM_.*</pattern>				
				<remoteFolderName>/ExtSD7/topodata/</remoteFolderName>
				<localFolderName>TWM/Lynx/actual_FTM</localFolderName>
				<putOrGet>0</putOrGet>
				<bulkTransport>1</bulkTransport>
				<compressPut>1</compressPut>
			</filePattern>
		</filePatterns>
	</server>
	<server serverName="iFM FTP server transporting iRM NBI datas">
		<ip>172.18.1.51</ip>
		<port>21</port>
		<userName>topouser</userName>
		<passwd>topouser</passwd>
		<sFtp>0</sFtp>
		
		<filePatterns>
			<filePattern description="NBI_file">
				<pattern>NBI_.*.zip</pattern>				
				<remoteFolderName>/ExtSD7/topodata/CarrierE</remoteFolderName>
				<localFolderName>UIM/NBI</localFolderName>
				<putOrGet>0</putOrGet>
				<bulkTransport>1</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>
		</filePatterns>
	</server>
	<server serverName="CE/ME config file datas">
		<ip>172.27.21.2</ip>
		<port>22</port>
		<userName>irmftp</userName>
		<passwd>irmftp123</passwd>
		<sFtp>1</sFtp>		
		<filePatterns>
			<filePattern description="CE/ME_file">
				<pattern>.*.gz</pattern>				
				<remoteFolderName>/var/me_cx_config/config</remoteFolderName>
				<localFolderName>UIM/CEMEconfig</localFolderName>
				<putOrGet>1</putOrGet>
				<bulkTransport>1</bulkTransport>
				<compressPut>0</compressPut>
			</filePattern>
		</filePatterns>
	</server>
</servers>
